name: 🐛 Bug Report
description: Report a bug or unexpected behavior
labels: [Bug 🐛]
body:
  - type: checkboxes
    attributes:
      label: Please confirm the following.
      options:
        - label: I checked the [existing issues](https://github.com/Illusioner2520/EnderLynx/issues?q=is%3Aissue) for duplicate problems
          required: true
        - label: I have ensured that EnderLynx is up to date
          required: true
  - type: input
    id: version
    attributes:
      label: What version of EnderLynx are you using?
      description: Find this in ⚙️ Settings -> App Info -> EnderLynx Version
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: false