name: ✨ Feature Request
description: Request a feature be added
labels: [Enchancement ✨]
body:
  - type: checkboxes
    attributes:
      label: Please confirm the following.
      options:
        - label: I checked the [existing issues](https://github.com/Illusioner2520/EnderLynx/issues?q=is%3Aissue) for duplicate feature requests
          required: true
  - type: textarea
    attributes:
      label: Describe the feature request
      description: A clear and concise description of what you want changed.
    validations:
      required: true